services:
  - type: web
    name: flask-arogy-server
    env: python
    plan: free
    buildCommand: cd others/server && pip install -r requirements.txt
    startCommand: cd others/server && gunicorn app:app
